### ISSUE TITLE
NFSU1 Server Emulator

### ISSUE THREAD

**Issue by janmarinka** [ian-travers/nc#1]
Hello,
I have seen the job you are doing to improve the server emulator for NFSU1 and its incredible. Unfortunatly I could not open a "issue" there since its a fork and I had no other way of contacting you. I would just like to show you some more issues I have found with the emulator. 
1) The challenge settings are not functional
![image](https://user-images.githubusercontent.com/56171849/169874098-43ebfad8-02c5-44d4-9a66-ad587105b3fa.png)
2) Despite gaining REP your rep in rooms is still 100 + User block is not functioning
![image](https://user-images.githubusercontent.com/56171849/169874444-6ca2b653-166c-4fb4-853e-5373ea0e5457.png)
3) Several stats I suspect not to be real/ user stats not implemented at all (Such as Overall Rank (maybe rep) and avg opposite rep and rank.
![image](https://user-images.githubusercontent.com/56171849/169874597-265ab052-6070-450c-b91e-719da85d9c51.png)

If you could be able to fix those issues, it would be amazing, if not, I am still very greatful for the work you have done to improve the original sourcecode.

Спасибо,
Jan.

**Comment by ian-travers** [comment]
Hello, @janmarinka!

"Head to Head -> Send Challenge" is causing the game to hang up. I couldn't figure out how it works. So you need to create a race instead.

Block player - I didn't even know what it did. Might be a complaint about a player. But I may be wrong. I don't think it will be implemented.

"Despite gaining REP your rep in rooms is still 100". Hmm, this should work. At least for RANKED GAME rooms. It’s a pity that I don’t have a working server on the Internet now, otherwise I could check.

About averages. 101 is the default for new usernames. The average reputation is calculated more or less correctly, which cannot be said about the average rating. if we could implement a record of the results of the race in a relational database, this would help.

**Comment by janmarinka** [comment]
I am from a team which works to revive servers for Need for Speed. I would love to make this fully work. Blocking players is basically blocking all interactions with the player. Until you unblock you wont see their chat messages, or cannot join a game with them. There is still a few stats that do not track properly which do need implementing. About challenging, it needs packet implementation so the server answers it properly and doesnt hang up.



благодарю вас,
Jan

**Comment by janmarinka** [comment]
If you have Discord, VK or Telegram you can add me there, it would be easier for us to chat there😁

**Comment by janmarinka** [comment]
I have done that. Now stats do seem to update correctly. About that "rank 9999" in everything, thats fictional right? Perhaps it needs implementing. Unfortunatly me myself I have not played the original EA server, however i do find RANK 9999 a little suspicious. About avg opp rep and rank, it is calculated correctly however then, a default rank should be 100 or 101 and counting... and not 9999. About head to head, ill try and look at what the game sends using the debug feature

**Comment by ian-travers** [comment]
Rank 9999 was the default in the EA server. When a player created an account and went to the RANKINGS - TOP 100, his username was 101 in the list with the RANK 9999. As I understand it, the EA server only displayed the rank for the first 10,000 players. Hundreds of thousands played in those days. Only by earning enough REP could a player get there. On the current server emulator, when there are only a few hundred players, it looks a little funny.

I've fixed the last bug.

**Comment by janmarinka** [comment]
Thanks for clearing the issue that rank 9999 was completely normal! Ill check on user block :)

**Comment by janmarinka** [comment]
Checked the block. Should be just a standard BLOCK packet. More concerned about challenge settings however

**Comment by ian-travers** [comment]
I've create a discussion on [nfsuserver](https://github.com/ian-travers/nfsuserver/discussions) for further conversations.
